spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: {YOUR MYSQLDB PASSWORD}
    url: {YOUR MYSQLDB LINK}
    username: {YOUR MYSQLDB USERNAME}
  data:
    mongodb:
      uri: {YOUR MANGODB URI}
      database: {YOUR MANGODB NAME}
  main:
    allow-bean-definition-overriding: true



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
