spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Ananth
    url: jdbc:mysql://localhost:3306/student
    username: root
  data:
    mongodb:
      uri: "mongodb+srv://sabarikarthiks04:sabari_2004@cluster0.d8rcwtv.mongodb.net/"
      database: "Student"
  main:
    allow-bean-definition-overriding: true



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true